name: Introspection CI

on:
  push:
    branches:
      - introspection
  pull_request:
    branches:
      - introspection

jobs:
  ubuntu-latest-aurora-build-and-run-failover-tests:
    name: 'Run Tests in `com.mysql.cj.jdbc'
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: 'Set up JDK 8'
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: 'Run Tests'
        run: |
          ./gradlew --no-parallel --no-daemon build test --tests "com.mysql.cj.jdbc.*"
      - name: Archive junit results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: junit-report
          path: build/reports/tests/
