name: 'Release to Maven'

on:
  release:
    types:
      - published

permissions:
  actions: write
  contents: write
  deployments: write
  packages: write
  pull-requests: write
  repository-projects: write

jobs:
  ubuntu-latest-aurora-build-and-release:
    name: 'Build And Release to Maven'
    runs-on: ubuntu-latest
    steps:
      - name: 'Clone Repository'
        uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: 'Set up JDK 8'
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: 'Publish to Maven'
        run: |
          ./gradlew --no-parallel --no-daemon --stacktrace publish \
            -Psigning.secretKeyRingFile=${{ secrets.GPG_PRIVATE_KEY }} \
            -Psigning.password=${{ secrets.GPG_PASSPHRASE }} \
            -Psigning.keyId=${{ secrets.GPG_KEY_ID }}
