name: 'Release to Maven'

on: [push]


permissions:
  actions: write
  contents: write
  deployments: write
  packages: write
  pull-requests: write
  repository-projects: write

jobs:
  ubuntu-latest-aurora-build-and-release:
    name: 'Build And Release to Maven'
    runs-on: ubuntu-latest
    steps:
      - name: 'Clone Repository'
        uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: 'Set up JDK 8'
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: 'Install GPG Secret Key'
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: "Decode Key Ring"
        run: |
          echo "${{secrets.GPG_SECRET_KEY_FILE}}" > ~/secring.gpg.b64
          base64 -d ~/secring.gpg.b64 > ~/secring.gpg
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
      - name: 'Publish to Maven'
        run: |
          ./gradlew --no-parallel --no-daemon publishAllPublicationsToOSSRHRepository \
            -Psigning.gnupg.secretKeyRingFile=$(echo ~/secring.gpg) \
            -Psigning.gnupg.passphrase=${{ secrets.GPG_PASSPHRASE }} \
            -Psigning.gnupg.keyName=${{ secrets.GPG_KEY_ID }}
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
